---
- name: update Sistema Operacional
  apt:  
    name: "*"

- name: instalando Nginx
  apt: name=nginx state=latest  
  become: true
  become_method: sudo

- name: Copiando index.html
  copy: 
    src: /ansible/templates/
    dest: /var/www/html
    remote_src: yes 
  become: true
  become_method: sudo


...
